Vagrant.configure("2") do |c|
  c.berkshelf.enabled = false if Vagrant.has_plugin?("vagrant-berkshelf")
  c.vm.box = "bento/centos-7.5"
  c.vm.hostname = "base-centos-75.vagrantup.com"
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.synced_folder "/Users/dm/Documents/DevOps/CHEF/INFRA/lcr-effortless-config-getting-started/results", "/tmp/results", nil
  c.vm.synced_folder "/Users/dm/.kitchen/cache", "/tmp/omnibus/cache", create: true
  c.vm.provider :virtualbox do |p|
    p.name = "kitchen-lcr-effortless-config-getting-started-base-centos-75-bc15533a-0266-40e7-b6be-e356b6045fea"
    p.customize ["modifyvm", :id, "--audio", "none"]
  end
end
