Vagrant.configure("2") do |c|
  c.berkshelf.enabled = false if Vagrant.has_plugin?("vagrant-berkshelf")
  c.vm.box = "bento/centos-7.5"
  c.vm.hostname = "base-centos-75.vagrantup.com"
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.synced_folder "/Users/dm/Documents/DevOps/CHEF/INFRA/lcr-effortless-config-getting-started/results", "/tmp/results", nil
  c.vm.synced_folder "/Users/dm/.kitchen/cache", "/tmp/omnibus/cache", create: true
  c.vm.provider :virtualbox do |p|
    p.name = "kitchen-lcr-effortless-config-getting-started-base-centos-75-fc01cc85-f2a9-4a19-b7f2-d75d6b7f1fdd"
    p.customize ["modifyvm", :id, "--audio", "none"]
  end
end
